name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3.2.0

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run Cypress tests in headless mode with cucumber reporting
      - name: Run Cypress tests and generate report
        run: npm run cypress:report

      # Upload Cypress test videos (optional)
      #      - name: Upload Cypress videos
      #        uses: actions/upload-artifact@v2
      #        with:
      #          name: cypress-videos
      #          path: cypress/videos

      # Upload Cypress screenshots (optional)
      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v3.2.0
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # Upload Cucumber HTML Report (optional)
      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v3.2.0
        with:
          name: cucumber-html-report
          path: cypress/reports/cucumber-report.html